package com.compact.floodar;

import android.content.Context;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * A place with known flood levels, loaded from assets/sites.json (generated by
 * db/export_sites.sh). The AR view renders a scenario's depth above the locally detected
 * ground plane, so a site can be viewed from anywhere ("teleport" mode).
 */
public final class FloodSite {
  private static final String ASSET = "sites.json";
  /** Optional personal sites (e.g. home), gitignored; same schema. */
  private static final String LOCAL_ASSET = "sites_local.json";
  private static final double METERS_PER_FOOT = 0.3048;

  /** One water level at a site: an observed event, a modeled recurrence, or an interpretation. */
  public static final class Scenario {
    public final String id;
    public final String label;
    /** "observed", "modeled", or "interpretation". */
    public final String kind;
    /** NaN when the level was observed relative to a surface rather than surveyed. */
    public final double wseFtNavd88;
    /** Water depth above ground at the site; negative means the site stayed dry. */
    public final double depthFt;
    public final String source;
    /** Surface the depth is measured from: "ground" (default), "street", or "porch". */
    public final String reference;

    Scenario(JSONObject o) throws JSONException {
      id = o.getString("id");
      label = o.getString("label");
      kind = o.getString("kind");
      wseFtNavd88 = o.optDouble("wse_ft_navd88", Double.NaN);
      depthFt = o.getDouble("depth_ft");
      source = o.optString("source", "");
      reference = o.optString("reference", "ground");
    }

    public double depthMeters() {
      return depthFt * METERS_PER_FOOT;
    }

    public boolean isDry() {
      return depthFt <= 0;
    }
  }

  /** Reconstructed 2010 Clear Lake surge marker; null for sites without one. */
  public static final class Marker {
    public final double heightFt;
    /** Bottom to top. Band heights are unknown; renderer must treat the split as provisional. */
    public final List<String> bandLabels;
    public final List<Integer> bandColors;

    Marker(JSONObject o) throws JSONException {
      heightFt = o.getDouble("height_ft");
      List<String> labels = new ArrayList<>();
      List<Integer> colors = new ArrayList<>();
      JSONArray bands = o.getJSONArray("bands");
      for (int i = 0; i < bands.length(); i++) {
        JSONObject b = bands.getJSONObject(i);
        labels.add(b.getString("label"));
        colors.add(android.graphics.Color.parseColor(b.getString("color")));
      }
      bandLabels = Collections.unmodifiableList(labels);
      bandColors = Collections.unmodifiableList(colors);
    }

    public double heightMeters() {
      return heightFt * METERS_PER_FOOT;
    }
  }

  public final String id;
  public final String name;
  public final String area;
  public final double lat;
  public final double lon;
  public final double groundFtNavd88;
  public final String note;
  public final Marker marker;
  public final List<Scenario> scenarios;

  private FloodSite(JSONObject o) throws JSONException {
    id = o.getString("id");
    name = o.getString("name");
    area = o.getString("area");
    lat = o.getDouble("lat");
    lon = o.getDouble("lon");
    groundFtNavd88 = o.getDouble("ground_ft_navd88");
    note = o.optString("note", "");
    marker = o.isNull("marker") ? null : new Marker(o.getJSONObject("marker"));
    List<Scenario> list = new ArrayList<>();
    JSONArray arr = o.getJSONArray("scenarios");
    for (int i = 0; i < arr.length(); i++) {
      list.add(new Scenario(arr.getJSONObject(i)));
    }
    scenarios = Collections.unmodifiableList(list);
  }

  public Scenario findScenario(String scenarioId) {
    for (Scenario s : scenarios) {
      if (s.id.equals(scenarioId)) {
        return s;
      }
    }
    return null;
  }

  public static final String CUSTOM_ID = "custom";

  /** A user-entered depth, measured from whatever surface the user taps. */
  public static FloodSite custom(double depthFt) {
    try {
      JSONObject sc =
          new JSONObject()
              .put("id", CUSTOM_ID)
              .put("label", "Custom depth")
              .put("kind", "interpretation")
              .put("reference", "floor or ground")
              .put("depth_ft", depthFt)
              .put("source", "Entered by the user");
      JSONObject o =
          new JSONObject()
              .put("id", CUSTOM_ID)
              .put("name", "Custom depth")
              .put("area", "Your choice")
              .put("lat", 0)
              .put("lon", 0)
              .put("ground_ft_navd88", 0)
              .put("marker", JSONObject.NULL)
              .put("scenarios", new JSONArray().put(sc));
      return new FloodSite(o);
    } catch (JSONException e) {
      throw new IllegalStateException(e);
    }
  }

  public static FloodSite find(List<FloodSite> sites, String siteId) {
    for (FloodSite s : sites) {
      if (s.id.equals(siteId)) {
        return s;
      }
    }
    return null;
  }

  /**
   * Loads all sites from assets: sites.json (required; throws if missing or malformed) followed
   * by sites_local.json if present.
   */
  public static List<FloodSite> loadAll(Context context) throws IOException, JSONException {
    List<FloodSite> sites = new ArrayList<>(load(context, ASSET));
    try {
      sites.addAll(load(context, LOCAL_ASSET));
    } catch (java.io.FileNotFoundException e) {
      // No personal sites in this build.
    }
    return Collections.unmodifiableList(sites);
  }

  private static List<FloodSite> load(Context context, String asset)
      throws IOException, JSONException {
    String json;
    try (InputStream in = context.getAssets().open(asset)) {
      ByteArrayOutputStream out = new ByteArrayOutputStream();
      byte[] buf = new byte[8192];
      for (int n; (n = in.read(buf)) != -1; ) {
        out.write(buf, 0, n);
      }
      json = out.toString(StandardCharsets.UTF_8.name());
    }
    JSONArray arr = new JSONObject(json).getJSONArray("sites");
    List<FloodSite> sites = new ArrayList<>();
    for (int i = 0; i < arr.length(); i++) {
      sites.add(new FloodSite(arr.getJSONObject(i)));
    }
    return sites;
  }
}
